### ISSUE TITLE
Optimise Enemy Objectives

### ISSUE THREAD

**Issue by trapw0w** [trapw0w/op_hammerfall#4]
`14:47:24 There are 205 objectives for this ["UK3CB_TKM_O"] OPCOM instance! Please lower the objective count for performance reasons, suggested is below 80!`

Look into the current MIL & CIV objectives within the TAOR. Implement proper testing to ensure that performance optimisation goals are met.

**Comment by LewisSO** [comment]
Fixed in commit 577073d. Appears to have reduced from upwards of 200 down to about 85. Much better.
